# pull python
FROM python:3.13.5-slim-bookworm

# install tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg libzbar0 libsodium-dev libopus0 \
    && rm -rf /var/lib/apt/lists/*

# install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# sync deps
WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-cache

# install playwright
RUN uv run playwright install --with-deps