# ----- build -----

# pull python
FROM python:3.13.5-slim-bookworm AS builder

# install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# install git
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# copy deps files
COPY pyproject.toml uv.lock ./

# install deps
ENV UV_LINK_MODE=copy
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project


# ----- run -----

# pull python
FROM python:3.13.5-slim-bookworm

# copy deps
COPY --from=builder /app/.venv /app/.venv
ENV PATH="/app/.venv/bin:$PATH"

# copy deno (for yt-dlp)
COPY --from=denoland/deno:bin-2.1.9 /deno /usr/local/bin/deno

# install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

# install tools and playwright
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        libzbar0 \
        libsodium23 \
        libopus0 && \
    uv run playwright install chromium --with-deps && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
